#!/bin/bash
set -euo pipefail

# === Injected by factory launch ===
DO_API_TOKEN="__DO_API_TOKEN__"
GH_TOKEN="__GH_TOKEN__"
REPO="__REPO__"
BRANCH="__BRANCH__"
SETUP_CMD="__SETUP_CMD__"
FACTORY_WEBHOOK_URL="__FACTORY_WEBHOOK_URL__"

# === Self-destruct on exit ===
DROPLET_ID=$(curl -s http://169.254.169.254/metadata/v1/id)

self_destruct() {
    echo "[factory] Self-destructing droplet $DROPLET_ID..."
    curl -s -X DELETE \
        -H "Authorization: Bearer $DO_API_TOKEN" \
        "https://api.digitalocean.com/v2/droplets/$DROPLET_ID"
}

# === Write secrets ===
cat > /root/.secrets <<SECRETS
export GH_TOKEN="$GH_TOKEN"
export DO_API_TOKEN="$DO_API_TOKEN"
export FACTORY_WEBHOOK_URL="$FACTORY_WEBHOOK_URL"
SECRETS
chmod 600 /root/.secrets

# === Install system dependencies ===
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq git curl jq unzip > /dev/null 2>&1

# Install GitHub CLI
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg 2>/dev/null
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
    | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
apt-get update -qq && apt-get install -y -qq gh > /dev/null 2>&1

# Install Node.js (for Claude Code)
curl -fsSL https://deb.nodesource.com/setup_22.x | bash - > /dev/null 2>&1
apt-get install -y -qq nodejs > /dev/null 2>&1

# Install Claude Code
npm install -g @anthropic-ai/claude-code > /dev/null 2>&1

# === Authenticate GitHub ===
echo "$GH_TOKEN" | gh auth login --with-token

# === Clone repo ===
gh repo clone "$REPO" /root/repo
cd /root/repo
if [ "$BRANCH" != "main" ] && [ "$BRANCH" != "" ]; then
    git checkout -b "$BRANCH"
fi

# === Run setup command ===
if [ -n "$SETUP_CMD" ] && [ "$SETUP_CMD" != "__SETUP_CMD__" ]; then
    echo "[factory] Running setup: $SETUP_CMD"
    eval "$SETUP_CMD"
fi

# === Write the agent runner script ===
cat > /root/agent-run.sh <<'AGENT'
#!/bin/bash
set -euo pipefail
source /root/.secrets

DROPLET_ID=$(curl -s http://169.254.169.254/metadata/v1/id)

self_destruct() {
    echo "[factory] Agent complete. Self-destructing droplet $DROPLET_ID..."
    curl -s -X DELETE \
        -H "Authorization: Bearer $DO_API_TOKEN" \
        "https://api.digitalocean.com/v2/droplets/$DROPLET_ID"
}
trap self_destruct EXIT

cd /root/repo
START_TIME=$(date +%s)

PLAN=$(cat /root/plan.md)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "[factory] Starting agent run at $(date)"
echo "[factory] Branch: $BRANCH"
echo "[factory] Plan: /root/plan.md"

AGENT_STATUS=0
claude -p "You are an autonomous coding agent. Execute the following implementation plan precisely.
Work through each step. Run tests if they exist. Commit your work as you go with clear commit messages.
When done, push your branch and create a pull request.

PLAN:
$PLAN" \
    --allowedTools "Read,Edit,Write,Bash,Glob,Grep,Agent" \
    --dangerously-skip-permissions \
    --max-turns 200 \
    --output-format stream-json \
    --verbose \
    > /root/agent.log 2>&1 || AGENT_STATUS=$?

echo "[factory] Agent finished at $(date)"

# Push and create PR if there are commits
if [ "$(git log origin/$BRANCH..$BRANCH 2>/dev/null | head -1)" != "" ] || [ "$BRANCH" != "main" ]; then
    git push -u origin "$BRANCH" 2>/dev/null || git push --set-upstream origin "$BRANCH"
    PR_URL=$(gh pr create \
        --title "factory: $(head -1 /root/plan.md | sed 's/^#* *//')" \
        --body "$(cat <<'EOF'
## Automated by Factory

This PR was generated by an autonomous Claude Code agent running on an ephemeral DigitalOcean droplet.

### Plan executed
$(cat /root/plan.md)

---
Review the changes carefully before merging.
EOF
)" 2>/dev/null) || PR_URL=""
    [ -z "$PR_URL" ] && echo "[factory] PR already exists or could not be created"
fi

# Send completion notification
if [ -n "${FACTORY_WEBHOOK_URL:-}" ]; then
    DROPLET_NAME=$(hostname)
    END_TIME=$(date +%s)
    DURATION=$(( (END_TIME - START_TIME) / 60 ))
    REPO_NAME=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo "unknown")

    if [ "$AGENT_STATUS" -eq 0 ]; then
        STATUS="success"
        TITLE="Agent finished: $REPO_NAME"
    else
        STATUS="failure"
        TITLE="Agent failed: $REPO_NAME"
    fi

    curl -s -X POST "$FACTORY_WEBHOOK_URL" \
        -H "Title: $TITLE" \
        -H "Tags: ${STATUS}" \
        -d "Branch: $BRANCH | Duration: ${DURATION}m | PR: ${PR_URL:-none} | Droplet: $DROPLET_NAME" \
        > /dev/null 2>&1 || true
fi

echo "[factory] Done. Droplet will self-destruct."
# trap fires self_destruct on exit
AGENT
chmod +x /root/agent-run.sh

# === Signal bootstrap complete ===
touch /root/.bootstrap-complete
echo "[factory] Bootstrap complete at $(date). Ready for auth + run."
