#!/bin/bash
set -euo pipefail

# cloud-init doesn't always set HOME
export HOME="/root"

# === Injected by factory launch ===
DO_API_TOKEN="__DO_API_TOKEN__"
GH_TOKEN="__GH_TOKEN__"
REPO="__REPO__"
BRANCH="__BRANCH__"
SETUP_CMD="__SETUP_CMD__"

# === Self-destruct on any exit (safety net for bootstrap failures) ===
DROPLET_ID=$(curl -s http://169.254.169.254/metadata/v1/id)

self_destruct() {
    echo "[factory] Self-destructing droplet $DROPLET_ID..."
    curl -s -X DELETE \
        -H "Authorization: Bearer $DO_API_TOKEN" \
        "https://api.digitalocean.com/v2/droplets/$DROPLET_ID"
}

# === Create non-root user (Claude Code refuses --dangerously-skip-permissions as root) ===
useradd -m -s /bin/bash factory
echo "factory ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/factory

FACTORY_HOME="/home/factory"

# === Write secrets ===
cat > "$FACTORY_HOME/.secrets" <<SECRETS
export GH_TOKEN="$GH_TOKEN"
export DO_API_TOKEN="$DO_API_TOKEN"
SECRETS
chmod 600 "$FACTORY_HOME/.secrets"
chown factory:factory "$FACTORY_HOME/.secrets"

# === Install system dependencies ===
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq git curl jq unzip > /dev/null 2>&1

# Install GitHub CLI
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg 2>/dev/null
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
    | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
apt-get update -qq && apt-get install -y -qq gh > /dev/null 2>&1

# Install Node.js (for Claude Code)
curl -fsSL https://deb.nodesource.com/setup_22.x | bash - > /dev/null 2>&1
apt-get install -y -qq nodejs > /dev/null 2>&1

# Install Claude Code
npm install -g @anthropic-ai/claude-code > /dev/null 2>&1

# === Configure git (as factory user) ===
su - factory -c 'git config --global user.name "Factory Agent"'
su - factory -c 'git config --global user.email "factory@noreply.github.com"'

# === Authenticate GitHub (as factory user) ===
su - factory -c "echo '$GH_TOKEN' | gh auth login --with-token"
su - factory -c "gh auth setup-git"

# === Clone repo (as factory user) ===
su - factory -c "gh repo clone '$REPO' '$FACTORY_HOME/repo'"
if [ "$BRANCH" != "main" ] && [ "$BRANCH" != "" ]; then
    su - factory -c "cd '$FACTORY_HOME/repo' && git checkout -b '$BRANCH'"
fi

# === Run setup command (if provided) ===
if [ -n "$SETUP_CMD" ] && [ "$SETUP_CMD" != "__SETUP_CMD__" ]; then
    echo "[factory] Running setup: $SETUP_CMD"
    su - factory -c "cd '$FACTORY_HOME/repo' && $SETUP_CMD"
fi

# === Write the agent runner script ===
cat > "$FACTORY_HOME/agent-run.sh" <<'AGENT'
#!/bin/bash
set -euo pipefail
source ~/.secrets

DROPLET_ID=$(curl -s http://169.254.169.254/metadata/v1/id)

self_destruct() {
    echo "[factory] Agent complete. Self-destructing droplet $DROPLET_ID..."
    curl -s -X DELETE \
        -H "Authorization: Bearer $DO_API_TOKEN" \
        "https://api.digitalocean.com/v2/droplets/$DROPLET_ID"
}
trap self_destruct EXIT

cd ~/repo

PLAN=$(cat ~/plan.md)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "[factory] Starting agent run at $(date)"
echo "[factory] Branch: $BRANCH"
echo "[factory] Plan: ~/plan.md"

claude -p "You are an autonomous coding agent. Execute the following implementation plan precisely.
Work through each step. Run tests if they exist. Commit your work as you go with clear commit messages.
Do NOT include 'Co-Authored-By' lines in any commit messages.
When done, push your branch and create a pull request.

PLAN:
$PLAN" \
    --allowedTools "Read,Edit,Write,Bash,Glob,Grep,Agent" \
    --dangerously-skip-permissions \
    --max-turns 200 \
    --output-format stream-json \
    --verbose \
    > ~/agent.log 2>&1

CLAUDE_EXIT=$?
echo "[factory] Agent finished at $(date) (exit code: $CLAUDE_EXIT)"

# Push and create PR if there are commits ahead of origin
COMMITS_AHEAD=$(git rev-list --count "origin/$BRANCH..$BRANCH" 2>/dev/null || echo "new")
if [ "$COMMITS_AHEAD" != "0" ]; then
    git push -u origin "$BRANCH"

    PR_BODY="## Automated by Factory

This PR was generated by an autonomous Claude Code agent running on an ephemeral DigitalOcean droplet.

### Plan executed
$(cat ~/plan.md)

---
Review the changes carefully before merging."

    gh pr create \
        --title "factory: $(head -1 ~/plan.md | sed 's/^#* *//')" \
        --body "$PR_BODY" \
        2>/dev/null || echo "[factory] PR already exists or could not be created"
fi

echo "[factory] Done. Droplet will self-destruct."
AGENT
chmod +x "$FACTORY_HOME/agent-run.sh"
chown factory:factory "$FACTORY_HOME/agent-run.sh"

# === Signal bootstrap complete ===
touch "$FACTORY_HOME/.bootstrap-complete"
# Also touch in /root so factory launch polling still works
touch /root/.bootstrap-complete
echo "[factory] Bootstrap complete at $(date). Ready for auth + run."
